solana account -u m 27G8MtK7VtTcCHkpASjSDdkWWYfoqT6ggEuKidVJidD4 --output-file 27G8MtK7VtTcCHkpASjSDdkWWYfoqT6ggEuKidVJidD4.json --output json-compact
solana account -u m 2KiAy13bDCMGfJ8MqbpTC7g3CunHjLQYMs3wK14XM5LZ --output-file 2KiAy13bDCMGfJ8MqbpTC7g3CunHjLQYMs3wK14XM5LZ.json --output json-compact
solana account -u m 2LecshUwdy9xi7meFgHtFJQNSKk4KdTrcpvaB56dP2NQ --output-file 2LecshUwdy9xi7meFgHtFJQNSKk4KdTrcpvaB56dP2NQ.json --output json-compact
solana account -u m 6NUiVmsNjsi4AfsMsEiaezsaV9N4N1ZrD4jEnuWNRvyb --output-file 6NUiVmsNjsi4AfsMsEiaezsaV9N4N1ZrD4jEnuWNRvyb.json --output json-compact
solana account -u m 7cs1chipprbrp8z84E7GX7WMf63Cgrohyi3r1W6gUGpu --output-file 7cs1chipprbrp8z84E7GX7WMf63Cgrohyi3r1W6gUGpu.json --output json-compact
solana account -u m 9EDgyY9m2LGGHt9ZRcprbDAjUFurWVUoH3HRZ4Cm963P --output-file 9EDgyY9m2LGGHt9ZRcprbDAjUFurWVUoH3HRZ4Cm963P.json --output json-compact
solana account -u m BH9LXGqLhZV3hdvShYZhgQQEjPVKhHPyHwjnsxjETFRr --output-file BH9LXGqLhZV3hdvShYZhgQQEjPVKhHPyHwjnsxjETFRr.json --output json-compact
solana account -u m Bz6Z63thYDzcs8ddLQ2CuoAMdK4QNjRhnr3RCLN5vciF --output-file Bz6Z63thYDzcs8ddLQ2CuoAMdK4QNjRhnr3RCLN5vciF.json --output json-compact
solana account -u m E8unvjyzG2QpaWWtV1s7uixeCW7QMs49Q2jQ86U19DjJ --output-file E8unvjyzG2QpaWWtV1s7uixeCW7QMs49Q2jQ86U19DjJ.json --output json-compact
solana account -u m EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v --output-file EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v.json --output json-compact
solana account -u m FGixaRkAbKtrL6bdaRwAgb9gXocYRMmn6m6betSdckZm --output-file FGixaRkAbKtrL6bdaRwAgb9gXocYRMmn6m6betSdckZm.json --output json-compact
solana account -u m GeBC3bZ6ixc6BMXpyuA9eZDxtDudjZYS8pZswWrijGVk --output-file GeBC3bZ6ixc6BMXpyuA9eZDxtDudjZYS8pZswWrijGVk.json --output json-compact
solana account -u m GoJSsR8AwPWCbbbFfwVtT97vTEdKs3kwGkahgvhiybMU --output-file GoJSsR8AwPWCbbbFfwVtT97vTEdKs3kwGkahgvhiybMU.json --output json-compact
solana account -u m J9twoKR2DfmyvE8HX6fDraaY2q5oECkHpZgtySiJkpsV --output-file J9twoKR2DfmyvE8HX6fDraaY2q5oECkHpZgtySiJkpsV.json --output json-compact