solana account -u m TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA   --output-file TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA.json --output json-compact  
solana account -u m 4xDsmeTWPNjgSVSS1VTfzFq3iHZhp77ffPkAmkZkdu71  --output-file 4xDsmeTWPNjgSVSS1VTfzFq3iHZhp77ffPkAmkZkdu71.json --output json-compact
solana account -u m EYxSnGjiyD2NfU8yBuGm6iUzmSdBaivJ9LEbgC8d7iHX  --output-file EYxSnGjiyD2NfU8yBuGm6iUzmSdBaivJ9LEbgC8d7iHX.json --output json-compact
solana account -u m AfA2VGGkcN2dtxuekM8oQgn3gZ9VdXznqkb3UWMCNj5S  --output-file AfA2VGGkcN2dtxuekM8oQgn3gZ9VdXznqkb3UWMCNj5S.json --output json-compact
solana account -u m m3BrPbv2TFmZZTPpyB9NgsCXqGNujpXvzvGqj8ksars   --output-file m3BrPbv2TFmZZTPpyB9NgsCXqGNujpXvzvGqj8ksars.json --output json-compact
solana account -u m 6zAcFYmxkaH25qWZW5ek4dk4SyQNpSza3ydSoUxjTudD  --output-file 6zAcFYmxkaH25qWZW5ek4dk4SyQNpSza3ydSoUxjTudD.json --output json-compact
solana account -u m 3fhzsLh8He3wcovSAXMw9fAJnneKGrf25csw3yVjuqb1  --output-file 3fhzsLh8He3wcovSAXMw9fAJnneKGrf25csw3yVjuqb1.json --output json-compact
solana account -u m EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v  --output-file EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v.json --output json-compact
solana account -u m JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4   --output-file JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4.json --output json-compact
solana account -u m D8cy77BBepLMngZx6ZukaTff5hCt1HrWyKk3Hnd9oitf  --output-file D8cy77BBepLMngZx6ZukaTff5hCt1HrWyKk3Hnd9oitf.json --output json-compact
solana account -u m MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr   --output-file MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr.json --output json-compact
solana account -u m HJPjoWUrhoZzkNfRpHuieeFk9WcZWjwy6PBjZ81ngndJ  --output-file HJPjoWUrhoZzkNfRpHuieeFk9WcZWjwy6PBjZ81ngndJ.json --output json-compact
solana account -u m 3YQm7ujtXWJU2e9jhp2QGHpnn1ShXn12QjvzMvDgabpX  --output-file 3YQm7ujtXWJU2e9jhp2QGHpnn1ShXn12QjvzMvDgabpX.json --output json-compact
solana account -u m 2JTw1fE2wz1SymWUQ7UqpVtrTuKjcd6mWwYwUJUCh2rq  --output-file 2JTw1fE2wz1SymWUQ7UqpVtrTuKjcd6mWwYwUJUCh2rq.json --output json-compact
solana account -u m HoDhUt77EotPNLUfJuvCCLbmpiM1JR6WLqWxeDPR1xvK  --output-file HoDhUt77EotPNLUfJuvCCLbmpiM1JR6WLqWxeDPR1xvK.json --output json-compact
solana account -u m 81T5kNuPRkyVzhwbe2RpKR7wmQpGJ7RBkGPdTqyfa5vq  --output-file 81T5kNuPRkyVzhwbe2RpKR7wmQpGJ7RBkGPdTqyfa5vq.json --output json-compact
solana account -u m 9K1HWrGKZKfjTnKfF621BmEQdai4FcUz9tsoF41jwz5B  --output-file 9K1HWrGKZKfjTnKfF621BmEQdai4FcUz9tsoF41jwz5B.json --output json-compact
solana account -u m 4GkRbcYg1VKsZropgai4dMf2Nj2PkXNLf43knFpavrSi  --output-file 4GkRbcYg1VKsZropgai4dMf2Nj2PkXNLf43knFpavrSi.json --output json-compact
