solana account EYxSnGjiyD2NfU8yBuGm6iUzmSdBaivJ9LEbgC8d7iHX  | grep -E "Public Key|Executable"
solana account 9yPGGsWnp395ca4cXHhbcDdrEkd13YCA2utErSX2wqRn  | grep -E "Public Key|Executable"
solana account CCTvoWRaXkh5tu1G7hxzqMQg1bu7fmopUJbZXe6XWvxq  | grep -E "Public Key|Executable"
solana account AfA2VGGkcN2dtxuekM8oQgn3gZ9VdXznqkb3UWMCNj5S  | grep -E "Public Key|Executable"
solana account EXrqY7jLTLp83H38L8Zw3GvGkk1KoQbYTckPGBghwD8X  | grep -E "Public Key|Executable" // token acc
solana account JChqfU7KQ2Tw5FKJAom57HsuU5u5Vo53arzSHAQ5nHKt  | grep -E "Public Key|Executable" // tc
solana account 6NUiVmsNjsi4AfsMsEiaezsaV9N4N1ZrD4jEnuWNRvyb  | grep -E "Public Key|Executable"
solana account 2KiAy13bDCMGfJ8MqbpTC7g3CunHjLQYMs3wK14XM5LZ  | grep -E "Public Key|Executable"
solana account GoJSsR8AwPWCbbbFfwVtT97vTEdKs3kwGkahgvhiybMU  | grep -E "Public Key|Executable"
solana account FGixaRkAbKtrL6bdaRwAgb9gXocYRMmn6m6betSdckZm  | grep -E "Public Key|Executable"
solana account Bz6Z63thYDzcs8ddLQ2CuoAMdK4QNjRhnr3RCLN5vciF  | grep -E "Public Key|Executable"
solana account J9twoKR2DfmyvE8HX6fDraaY2q5oECkHpZgtySiJkpsV  | grep -E "Public Key|Executable"
solana account 8HchJS2ufNvZv6i3Q6zRLvBDpVe1P72ArR86p2hUHvg6  | grep -E "Public Key|Executable"
solana account ComputeBudget111111111111111111111111111111 | grep -E "Public Key|Executable"
solana account 4C3kEWG1tqTEWfh9oAhuqGSDA68bcBHGVQbZqUqx3hx9  | grep -E "Public Key|Executable"
solana account So11111111111111111111111111111111111111112 | grep -E "Public Key|Executable"
solana account JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4 | grep -E "Public Key|Executable"
solana account TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA | grep -E "Public Key|Executable"
solana account 9nnLbotNTcUhvbrsA6Mdkx45Sm82G35zo28AqUvjExn8  | grep -E "Public Key|Executable"
solana account EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v  | grep -E "Public Key|Executable"
solana account 27G8MtK7VtTcCHkpASjSDdkWWYfoqT6ggEuKidVJidD4  | grep -E "Public Key|Executable"
solana account D8cy77BBepLMngZx6ZukaTff5hCt1HrWyKk3Hnd9oitf  | grep -E "Public Key|Executable"
solana account whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc | grep -E "Public Key|Executable"
solana account MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr | grep -E "Public Key|Executable"